<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

/*
|--------------------------------------------------------------------------
| Base Site URL
|--------------------------------------------------------------------------
|
| URL to your CodeIgniter root. Typically this will be your base URL,
| WITH a trailing slash:
|
|	http://example.com/
|
| If this is not set then CodeIgniter will guess the protocol, domain and
| path to your installation.
|
*/
$config['base_url']	= "http://".$_SERVER['SERVER_NAME']."/";

/*
|--------------------------------------------------------------------------
| Index File
|--------------------------------------------------------------------------
|
| Typically this will be your index.php file, unless you've renamed it to
| something else. If you are using mod_rewrite to remove the page set this
| variable so that it is blank.
|
*/
$config['index_page'] = 'index.php';

/*
|--------------------------------------------------------------------------
| URI PROTOCOL
|--------------------------------------------------------------------------
|
| This item determines which server global should be used to retrieve the
| URI string.  The default setting of 'AUTO' works for most servers.
| If your links do not seem to work, try one of the other delicious flavors:
|
| 'AUTO'			Default - auto detects
| 'PATH_INFO'		Uses the PATH_INFO
| 'QUERY_STRING'	Uses the QUERY_STRING
| 'REQUEST_URI'		Uses the REQUEST_URI
| 'ORIG_PATH_INFO'	Uses the ORIG_PATH_INFO
|
*/
$config['uri_protocol']	= 'AUTO';

/*
|--------------------------------------------------------------------------
| URL suffix
|--------------------------------------------------------------------------
|
| This option allows you to add a suffix to all URLs generated by CodeIgniter.
| For more information please see the user guide:
|
| http://codeigniter.com/user_guide/general/urls.html
*/

$config['url_suffix'] = '';

/*
|--------------------------------------------------------------------------
| Default Language
|--------------------------------------------------------------------------
|
| This determines which set of language files should be used. Make sure
| there is an available translation if you intend to use something other
| than english.
|
*/
$config['language']	= 'english';

/*
|--------------------------------------------------------------------------
| Default Character Set
|--------------------------------------------------------------------------
|
| This determines which character set is used by default in various methods
| that require a character set to be provided.
|
*/
$config['charset'] = 'UTF-8';

/*
|--------------------------------------------------------------------------
| Enable/Disable System Hooks
|--------------------------------------------------------------------------
|
| If you would like to use the 'hooks' feature you must enable it by
| setting this variable to TRUE (boolean).  See the user guide for details.
|
*/
$config['enable_hooks'] = FALSE;


/*
|--------------------------------------------------------------------------
| Class Extension Prefix
|--------------------------------------------------------------------------
|
| This item allows you to set the filename/classname prefix when extending
| native libraries.  For more information please see the user guide:
|
| http://codeigniter.com/user_guide/general/core_classes.html
| http://codeigniter.com/user_guide/general/creating_libraries.html
|
*/
$config['subclass_prefix'] = 'MY_';


/*
|--------------------------------------------------------------------------
| Allowed URL Characters
|--------------------------------------------------------------------------
|
| This lets you specify with a regular expression which characters are permitted
| within your URLs.  When someone tries to submit a URL with disallowed
| characters they will get a warning message.
|
| As a security measure you are STRONGLY encouraged to restrict URLs to
| as few characters as possible.  By default only these are allowed: a-z 0-9~%.:_-
|
| Leave blank to allow all characters -- but only if you are insane.
|
| DO NOT CHANGE THIS UNLESS YOU FULLY UNDERSTAND THE REPERCUSSIONS!!
|
*/
$config['permitted_uri_chars'] = 'a-z 0-9~%.:_\-';


/*
|--------------------------------------------------------------------------
| Enable Query Strings
|--------------------------------------------------------------------------
|
| By default CodeIgniter uses search-engine friendly segment based URLs:
| example.com/who/what/where/
|
| By default CodeIgniter enables access to the $_GET array.  If for some
| reason you would like to disable it, set 'allow_get_array' to FALSE.
|
| You can optionally enable standard query string based URLs:
| example.com?who=me&what=something&where=here
|
| Options are: TRUE or FALSE (boolean)
|
| The other items let you set the query string 'words' that will
| invoke your controllers and its functions:
| example.com/index.php?c=controller&m=function
|
| Please note that some of the helpers won't work as expected when
| this feature is enabled, since CodeIgniter is designed primarily to
| use segment based URLs.
|
*/
$config['allow_get_array']		= TRUE;
$config['enable_query_strings'] = FALSE;
$config['controller_trigger']	= 'c';
$config['function_trigger']		= 'm';
$config['directory_trigger']	= 'd'; // experimental not currently in use

/*
|--------------------------------------------------------------------------
| Error Logging Threshold
|--------------------------------------------------------------------------
|
| If you have enabled error logging, you can set an error threshold to
| determine what gets logged. Threshold options are:
| You can enable error logging by setting a threshold over zero. The
| threshold determines what gets logged. Threshold options are:
|
|	0 = Disables logging, Error logging TURNED OFF
|	1 = Error Messages (including PHP errors)
|	2 = Debug Messages
|	3 = Informational Messages
|	4 = All Messages
|
| For a live site you'll usually only enable Errors (1) to be logged otherwise
| your log files will fill up very fast.
|
*/
$config['log_threshold'] = 0;

/*
|--------------------------------------------------------------------------
| Error Logging Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/logs/ folder. Use a full server path with trailing slash.
|
*/
$config['log_path'] = '';

/*
|--------------------------------------------------------------------------
| Date Format for Logs
|--------------------------------------------------------------------------
|
| Each item that is logged has an associated date. You can use PHP date
| codes to set your own date formatting
|
*/
$config['log_date_format'] = 'Y-m-d H:i:s';

/*
|--------------------------------------------------------------------------
| Cache Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| system/cache/ folder.  Use a full server path with trailing slash.
|
*/
$config['cache_path'] = '';

/*
|--------------------------------------------------------------------------
| Encryption Key
|--------------------------------------------------------------------------
|
| If you use the Encryption class or the Session class you
| MUST set an encryption key.  See the user guide for info.
|
*/
$config['encryption_key'] = 'WIRELESS_SESSION';

/*
|--------------------------------------------------------------------------
| Session Variables
|--------------------------------------------------------------------------
|
| 'sess_cookie_name'		= the name you want for the cookie
| 'sess_expiration'			= the number of SECONDS you want the session to last.
|   by default sessions last 7200 seconds (two hours).  Set to zero for no expiration.
| 'sess_expire_on_close'	= Whether to cause the session to expire automatically
|   when the browser window is closed
| 'sess_encrypt_cookie'		= Whether to encrypt the cookie
| 'sess_use_database'		= Whether to save the session data to a database
| 'sess_table_name'			= The name of the session database table
| 'sess_match_ip'			= Whether to match the user's IP address when reading the session data
| 'sess_match_useragent'	= Whether to match the User Agent when reading the session data
| 'sess_time_to_update'		= how many seconds between CI refreshing Session Information
|
*/
$config['sess_cookie_name']		= 'ci_session';
$config['sess_expiration']		= 7200;
$config['sess_expire_on_close']	= FALSE;
$config['sess_encrypt_cookie']	= FALSE;
$config['sess_use_database']	= FALSE;
$config['sess_table_name']		= 'ci_sessions';
$config['sess_match_ip']		= FALSE;
$config['sess_match_useragent']	= TRUE;
$config['sess_time_to_update']	= 300;

/*
|--------------------------------------------------------------------------
| Cookie Related Variables
|--------------------------------------------------------------------------
|
| 'cookie_prefix' = Set a prefix if you need to avoid collisions
| 'cookie_domain' = Set to .your-domain.com for site-wide cookies
| 'cookie_path'   =  Typically will be a forward slash
| 'cookie_secure' =  Cookies will only be set if a secure HTTPS connection exists.
|
*/
$config['cookie_prefix']	= "";
$config['cookie_domain']	= "";
$config['cookie_path']		= "/";
$config['cookie_secure']	= FALSE;

/*
|--------------------------------------------------------------------------
| Global XSS Filtering
|--------------------------------------------------------------------------
|
| Determines whether the XSS filter is always active when GET, POST or
| COOKIE data is encountered
|
*/
$config['global_xss_filtering'] = FALSE;

/*
|--------------------------------------------------------------------------
| Cross Site Request Forgery
|--------------------------------------------------------------------------
| Enables a CSRF cookie token to be set. When set to TRUE, token will be
| checked on a submitted form. If you are accepting user data, it is strongly
| recommended CSRF protection be enabled.
|
| 'csrf_token_name' = The token name
| 'csrf_cookie_name' = The cookie name
| 'csrf_expire' = The number in seconds the token should expire.
*/
$config['csrf_protection'] = FALSE;
$config['csrf_token_name'] = 'csrf_test_name';
$config['csrf_cookie_name'] = 'csrf_cookie_name';
$config['csrf_expire'] = 7200;

/*
|--------------------------------------------------------------------------
| Output Compression
|--------------------------------------------------------------------------
|
| Enables Gzip output compression for faster page loads.  When enabled,
| the output class will test whether your server supports Gzip.
| Even if it does, however, not all browsers support compression
| so enable only if you are reasonably sure your visitors can handle it.
|
| VERY IMPORTANT:  If you are getting a blank page when compression is enabled it
| means you are prematurely outputting something to your browser. It could
| even be a line of whitespace at the end of one of your scripts.  For
| compression to work, nothing can be sent before the output buffer is called
| by the output class.  Do not 'echo' any values with compression enabled.
|
*/
$config['compress_output'] = FALSE;

/*
|--------------------------------------------------------------------------
| Master Time Reference
|--------------------------------------------------------------------------
|
| Options are 'local' or 'gmt'.  This pref tells the system whether to use
| your server's local time as the master 'now' reference, or convert it to
| GMT.  See the 'date helper' page of the user guide for information
| regarding date handling.
|
*/
$config['time_reference'] = 'local';


/*
|--------------------------------------------------------------------------
| Rewrite PHP Short Tags
|--------------------------------------------------------------------------
|
| If your PHP installation does not have short tag support enabled CI
| can rewrite the tags on-the-fly, enabling you to utilize that syntax
| in your view files.  Options are TRUE or FALSE (boolean)
|
*/
$config['rewrite_short_tags'] = FALSE;


/*
|--------------------------------------------------------------------------
| Reverse Proxy IPs
|--------------------------------------------------------------------------
|
| If your server is behind a reverse proxy, you must whitelist the proxy IP
| addresses from which CodeIgniter should trust the HTTP_X_FORWARDED_FOR
| header in order to properly identify the visitor's IP address.
| Comma-delimited, e.g. '10.0.1.200,10.0.1.201'
|
*/
$config['proxy_ips'] = '';

$config['photo_path'] = str_replace('//', '/', $_SERVER['DOCUMENT_ROOT'].'/static/photo/');
$config['photo_url'] = '/static/photo/';
$config['photo_zip'] = str_replace('//', '/', $_SERVER['DOCUMENT_ROOT'].'/static/zip/');

/* End of file config.php */
/* Location: ./application/config/config.php */

/*权限设置*/
$config['permission'] = array(
	0=>array('会员列表','会员权限',array('user','index'),array('user','profile')),
	1=>array('修改会员信息','会员权限',array('user','profile'),array('user','save'),array('user','cardno'),array('user','addremark'),array('user','saveremark'),array('user','newpici'),array('user','huanzheng')),
	2=>array('添加会员','会员权限',array('user','add'),array('user','save'),array('user','cardno'),array('user','addgroup'),array('user','savegroup'),array('user','addremark'),array('user','saveremark')),
	13=>array('导出会员信息','会员权限',array('user','export'),array('user','exportrun')),
	29=>array('导入会员信息','会员权限',array('user','import'),array('user','importrun')),
	14=>array('专业信息维护','会员权限',array('user','profession'),array('user','profession_run')),
	15=>array('照片拍摄','会员权限',array('user','camera'),array('user','upload')),
	26=>array('照片上传','会员权限',array('user','camera'),array('user','fileupload')),
	25=>array('照片管理','会员权限',array('user','photodel'),array('user','setphoto')),
	16=>array('会员缴费','会员权限',
		array('user','pay'),
		array('user','pay_type'),
		array('user','payprint'),
		array('user','payrun'),
		array('user','list0'),
		array('user','list1'),
		array('user','list2'),
		array('user','list3'),
		array('user','list4'),
		array('user','list5'),
		array('user','list6'),
		array('user','list7'),
		array('user','list8'),
		array('user','list9')),
	17=>array('会员缴费记录','会员权限',array('user','paylist'),array('user','paydel')),
	18=>array('打印执照','会员权限',array('user','zhizhao'),array('user','zhizhaoprint')),
	19=>array('批量生成呼号','会员权限',array('user','huhao'),array('user','sethuhao'),array('user','huhaorun')),
	12=>array('会员考试管理','会员权限',array('user','pass'),array('user','passb'),array('user','passc'),array('user','list100'),array('user','list104'),array('user','list105')),
	30=>array('会员验机','会员权限',array('user','list101')),
	34=>array('会员签到','会员权限',array('user','list103'),array('user','qiandao')),
	28=>array('考试刷卡通过','会员权限',array('user','cardpass')),
	33=>array('解决待处理问题','会员权限',array('user','remarklist'),array('user','remark'),array('user','operateremark')),
	36=>array('导出付费详情','会员权限',array('user','paydata'),array('user','paydatarun')),
	37=>array('补打执照','会员权限',array('user','budazhizhao')),

	3=>array('查看设备','设备权限',array('device','index')),
	4=>array('修改设备','设备权限',array('device','detail'),array('device','save')),
	5=>array('添加设备','设备权限',array('device','add'),array('device','save')),
	20=>array('设备验机','设备权限',array('device','yanji')),
	31=>array('删除设备','设备权限',array('device','deletedev')),
	32=>array('恢复设备','设备权限',array('device','recoverdev')),

	6=>array('查看费用金额','系统设置',array('set','pay')),
	7=>array('修改费用金额','系统设置',array('set','payedit'),array('set','payrun')),
	8=>array('查看费用历史','系统设置',array('set','paylist')),
	9=>array('注册批次管理','系统设置',array('set','pici'),array('set','piciadd'),array('set','picirun'),array('set','picidel'),array('set','pichuanzheng')),
	21=>array('验机批次管理','系统设置',array('set','yanjipici'),array('set','yanjipiciadd'),array('set','yanjipicirun'),array('set','yanjipicidel'),array('set','yanjipicisub'),array('user','list102'),array('user','yanjideluser')),
	10=>array('级别设置','系统设置',array('set','level'),array('set','leveladd'),array('set','levelrun'),array('set','leveldel')),
	35=>array('会费年限设置','系统设置',array('set','payyear'),array('set','payyearrun')),
	11=>array('修改密码','系统设置',array('set','pwd'),array('set','pwdrun')),
	27=>array('查看操作日志','系统设置',array('set','log')),

	22=>array('账号列表','账号管理',array('set','adminlist')),
	23=>array('冻结账号','账号管理',array('set','freezeadmin')),
	24=>array('添加/编辑管理员','账号管理',array('set','adminedit'),array('set','adminrun')),

	//25=>array('系统首页','系统首页',array('index','index'),array('index','index')),
);

$config['pay_type'] = array(
	0=>array('会费',true,false),//array(类别名称,有效期一年,是否可以重复缴纳)
	1=>array('培训费',false,false),
	2=>array('制证费',false,true),
	3=>array('组网费',false,false),
	4=>array('挂号费',true,false),
	5=>array('换照费',false,false),
	6=>array('操作证费',false,true),
	7=>array('报名考试费',false,true),
	8=>array('B级考试费',false,true),
	9=>array('C级考试费',false,true),
	//10=>array('C级考试费',false,true),
);

$config['test_times'] = array(
	'A'=>2,
	'B'=>1,
	'C'=>1,
);

$config['lv_to_int'] = array(
	'A'=>4,
	'B'=>3,
	'C'=>1,
);


$config['pay_type_print'] = array(
	0=>'会费',
	1=>'培训费',
	2=>'制证费',
	3=>'信息采集费',//组网费
	4=>'挂号费',
	5=>'信息采集费',//换照费
	6=>'操作证费',
	7=>'报名考试费',
	8=>'B级考试费',
	9=>'C级考试费',
);
/*系统使用的常用数组*/
$config['global'] = array(
	'status'	=>	array(-1=>'已删除',0=>'未审核',1=>'状态正常',2=>'待定'),	//通用状态
	'device_type'	=>	array(1=>'车载UV电台',2=>'手持UV电台',3=>'固定UV电台',4=>'短波电台'),		//设备类型
	'yes_or_no'	=>	array(0=>'否',1=>'是'),			//是否
	'gender'	=>	array('男'=>'男','女'=>'女'),			//性别
	'admin_status'	=>	array(0=>'冻结',1=>'正常'),			//管理员状态
	'degree'	=>	array('大学','高中','初中'),			//学历
	'power'	=>	array('A'=>'0','B'=>'100','C'=>'1000'),			//设备发射功率和级别的关系
	'def_power'	=>	array(1=>'25',2=>'25',3=>'25',4=>''),			//设备发射功率和级别的关系
	'user_type'	=>	array(1=>'个人会员',2=>'集体会员'),			//集体台和个人台
	'profession_edit'	=>	array(
		//0=>array('PA码','pa'),
		1=>array('呼号','huhao'),
		//2=>array('brsa会员证号','membernum'),
		3=>array('crac会员证号','crac_id'),
		4=>array('操作等级','Oplev'),
		5=>array('考试是否通过','test_pass'),
		6=>array('验机批次(执照打印批次)','yanjipid'),
		),
	'log_type'	=>	array('user'=>'用户操作(包括付费)','device'=>'设备操作','set'=>'系统设置'),
);

$config['area']['11']	=	array(
	'东城区',
	'西城区',
	'崇文区',
	'宣武区',
	'朝阳区',
	'海淀区',
	'丰台区',
	'石景山区',
	'通州区',
	'平谷区',
	'顺义区',
	'怀柔区',
	'昌平区',
	'门头沟区',
	'房山区',
	'大兴区',
	'密云县',
	'延庆县'
);

$config['province']	=	array('北京市',
	'天津市',
	'上海市',
	'重庆市',
	'香港特别行政区',
	'澳门特别行政区',
	'河北省',
	'山西省',
	'内蒙古自治区',
	'辽宁省',
	'吉林省',
	'黑龙江省',
	'江苏省',
	'浙江省',
	'安徽省',
	'福建省',
	'江西省',
	'山东省',
	'河南省',
	'湖北省',
	'湖南省',
	'广东省',
	'广西壮族自治区',
	'海南省',
	'四川省',
	'贵州省',
	'云南省',
	'西藏自治区',
	'陕西省',
	'甘肃省',
	'青海省',
	'宁夏回族自治区',
	'新疆维吾尔自治区',
	'台湾省');

$config['user_export'] = array(
	'userIDcard'	=>	'身份证件号',
	'username'	=>	'姓名',
	'usersex'	=>	'性别',
	'userbirthday'	=>	'出生日期',
	'huhao'	=>	'原指配的电台呼号',
	'Oplev'	=>	'核准操作类别',
	'pass_time'	=>	'通过日期',

	'area'	=>	'地市县',
	'uid'	=>	'系统id',
	'ID'	=>	'',
	'user_name_new'	=>	'',
	'userpinyin'	=>	'姓名拼音',
	'userminzu'	=>	'民族',
	'userwenhua'	=>	'学历',
	'yyzz'	=>	'营业执照编号',
	'zzjg'	=>	'组织机构代码',
	'workTel'	=>	'工作电话',
	'homeTel'	=>	'家庭电话',
	'mobTel'	=>	'手机',
	'mail'	=>	'电子邮件',
	'txAd'	=>	'通讯地址',
	'txpost'	=>	'通讯邮政编码',
	'xzAd'	=>	'户籍地址',
	'xzpost'	=>	'户籍邮政编码',
	'stAd'	=>	'设台地址',
	'stpost'	=>	'设台邮政编码',
	'company'	=>	'公司',
	'zhiwu'	=>	'职务',
	'workAd'	=>	'工作地址',
	'workAdPost'	=>	'工作邮政编码',
	'zhucetime'	=>	'注册时间',
	'zhuceAd'	=>	'注册地点',
	'opquhao'	=>	'操作证区号',
	'membernum'	=>	'brsa会员号',
	'crac_id'	=>	'crac会员号',
	'clubname'	=>	'',
	'zhuguanname'	=>	'',
	'taitype'	=>	'',
	'ziliaoBH'	=>	'',
	'taiAd'	=>	'',
	'level_old'	=>	'',
	'OpzhengBH'	=>	'',
	'huhao_old'	=>	'',
	'huhao_new'	=>	'',
	'pa'	=>	'申请编号',
	'pa_old'	=>	'',
	'devcount'	=>	'',
	'devSCLMcount'	=>	'',
	'devCZLMcount'	=>	'',
	'devVcount'	=>	'',
	'devHcount'	=>	'',
	'cardno'	=>	'',
	'IsJF'	=>	'',
	'isyj'	=>	'',	//用是否有未验机的设备1表示是，0表示否，和device_info正好相反
	'balance'	=>	'',
	'pci'	=>	'注册批次',
	'change_pici'	=>	'',
	'levelatime'	=>	'',
	'levelbtime'	=>	'',
	'levelctime'	=>	'',
	'levOneTime'	=>	'',
	'levTwoTime'	=>	'',
	'levThreeTime'	=>	'',
	'levFourTime'	=>	'',
	'huhaoTime'	=>	'',
	'huhaotime_old'	=>	'',
	'IsPX'	=>	'',
	'test_charge'	=>	'',
	'test_times'	=>	'',
	'test_pass'	=>	'考试是否通过',
	'createtime'	=>	'',
	'modifytime'	=>	'',
	'createadmin'	=>	'',
	'modifyadmin'	=>	'',

	'pid'	=>	'',	//会员照片id，不在user_info表
);

$config['user_export_wgj'] = array(
	'userIDcard'	=>	'证件号',
	'username'	=>	'姓名',
	'usersex'	=>	'性别',
	'userbirthday'	=>	'出生日期',
	'huhao'	=>	'原指配的电台呼号',
	'Oplev'	=>	'核准操作类别',
	'zhucetime'	=>	'注册时间',
	//'pass_time'	=>	'通过日期',
	'no_exp_test'	=>	array('考场名称','北京市'),
	'no_exp_dt'	=>	array('核发日期',date('Y.m.d')),
	'no_exp_ad'	=>	array('核发地点','北京市'),
	//'crac_id'	=>	'crac会员号',
	'crac_id'	=>	'crac会员号',
	'no_exp_pro'	=>	array('省市区','北京市'),
	'area'	=>	'地市县',
	'txAd'	=>	'地址',
	'txpost'	=>	'邮编',
	'mobTel'	=>	'电话',
	'mail'	=>	'邮件',
	'no_exp_qq'	=>	array('QQ号',''),
	'no_exp_desc'	=>	array('备注',''),

	'uid'	=>	'',
	'ID'	=>	'',
	'user_name_new'	=>	'',
	'userpinyin'	=>	'',
	'userminzu'	=>	'',
	'userwenhua'	=>	'',
	'workTel'	=>	'',
	'homeTel'	=>	'',
	'pass_time'	=>	'',


	'xzAd'	=>	'',
	'xzpost'	=>	'',
	'stAd'	=>	'',
	'stpost'	=>	'',
	'company'	=>	'',
	'zhiwu'	=>	'',
	'workAd'	=>	'',
	'workAdPost'	=>	'',
	//'zhucetime'	=>	'',
	'zhuceAd'	=>	'',
	'opquhao'	=>	'',
	'membernum'	=>	'',
	'clubname'	=>	'',
	'zhuguanname'	=>	'',
	'taitype'	=>	'',
	'ziliaoBH'	=>	'',
	'taiAd'	=>	'',
	'level_old'	=>	'',
	'OpzhengBH'	=>	'',
	'huhao_old'	=>	'',
	'huhao_new'	=>	'',
	'pa'	=>	'',
	'pa_old'	=>	'',
	'devcount'	=>	'',
	'devSCLMcount'	=>	'',
	'devCZLMcount'	=>	'',
	'devVcount'	=>	'',
	'devHcount'	=>	'',
	'cardno'	=>	'',
	'IsJF'	=>	'',
	'IsYJ'	=>	'',
	'balance'	=>	'',
	'pci'	=>	'',
	'change_pici'	=>	'',
	'levelatime'	=>	'',
	'levelbtime'	=>	'',
	'levelctime'	=>	'',
	'levOneTime'	=>	'',
	'levTwoTime'	=>	'',
	'levThreeTime'	=>	'',
	'levFourTime'	=>	'',
	'huhaoTime'	=>	'',
	'huhaotime_old'	=>	'',
	'IsPX'	=>	'',
	'test_charge'	=>	'',
	'test_times'	=>	'',
	'test_pass'	=>	'',
	'createtime'	=>	'',
	'modifytime'	=>	'',
	'createadmin'	=>	'',
	'modifyadmin'	=>	'',

	'pid'	=>	'',	//会员照片id，不在user_info表
);